name: Convert ADOC to PDF

on:
  push:
    paths:
      - '**/*.adoc'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Asciidoctor and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby
          gem install asciidoctor asciidoctor-pdf

      - name: Convert ADOC to PDF
        run: |
          asciidoctor-pdf <filename>.adoc

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: converted-pdf
          path: <filename>.pdf
